from http import HTTPStatus
from typing import Any

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.error import Error
from ...models.http_validation_error import HTTPValidationError
from ...models.todo import Todo
from ...models.todo_create import TodoCreate
from ...types import UNSET, Response, Unset


def _get_kwargs(
    *,
    body: TodoCreate | Unset = UNSET,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}

    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": "/todos",
    }

    if not isinstance(body, Unset):
        _kwargs["json"] = body.to_dict()

    headers["Content-Type"] = "application/json"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Error | HTTPValidationError | Todo | None:
    if response.status_code == 200:
        response_200 = Todo.from_dict(response.json())

        return response_200

    if response.status_code == 201:
        response_201 = Todo.from_dict(response.json())

        return response_201

    if response.status_code == 400:
        response_400 = Error.from_dict(response.json())

        return response_400

    if response.status_code == 422:
        response_422 = HTTPValidationError.from_dict(response.json())

        return response_422

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Error | HTTPValidationError | Todo]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient | Client,
    body: TodoCreate | Unset = UNSET,
) -> Response[Error | HTTPValidationError | Todo]:
    """TODO作成

     新しいTODOを作成する

    Args:
        body (TodoCreate | Unset): NOTE: This class is auto generated by OpenAPI Generator
            (https://openapi-generator.tech).

            Do not edit the class manually.

            TodoCreate - a model defined in OpenAPI

                project_id: The project_id of this TodoCreate [Optional].
                worker_id: The worker_id of this TodoCreate.
                agent_id: The agent_id of this TodoCreate [Optional].
                title: The title of this TodoCreate.
                description: The description of this TodoCreate [Optional].
                status: The status of this TodoCreate [Optional].
                priority: The priority of this TodoCreate [Optional].
                due_date: The due_date of this TodoCreate [Optional].

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | HTTPValidationError | Todo]
    """

    kwargs = _get_kwargs(
        body=body,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient | Client,
    body: TodoCreate | Unset = UNSET,
) -> Error | HTTPValidationError | Todo | None:
    """TODO作成

     新しいTODOを作成する

    Args:
        body (TodoCreate | Unset): NOTE: This class is auto generated by OpenAPI Generator
            (https://openapi-generator.tech).

            Do not edit the class manually.

            TodoCreate - a model defined in OpenAPI

                project_id: The project_id of this TodoCreate [Optional].
                worker_id: The worker_id of this TodoCreate.
                agent_id: The agent_id of this TodoCreate [Optional].
                title: The title of this TodoCreate.
                description: The description of this TodoCreate [Optional].
                status: The status of this TodoCreate [Optional].
                priority: The priority of this TodoCreate [Optional].
                due_date: The due_date of this TodoCreate [Optional].

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | HTTPValidationError | Todo
    """

    return sync_detailed(
        client=client,
        body=body,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient | Client,
    body: TodoCreate | Unset = UNSET,
) -> Response[Error | HTTPValidationError | Todo]:
    """TODO作成

     新しいTODOを作成する

    Args:
        body (TodoCreate | Unset): NOTE: This class is auto generated by OpenAPI Generator
            (https://openapi-generator.tech).

            Do not edit the class manually.

            TodoCreate - a model defined in OpenAPI

                project_id: The project_id of this TodoCreate [Optional].
                worker_id: The worker_id of this TodoCreate.
                agent_id: The agent_id of this TodoCreate [Optional].
                title: The title of this TodoCreate.
                description: The description of this TodoCreate [Optional].
                status: The status of this TodoCreate [Optional].
                priority: The priority of this TodoCreate [Optional].
                due_date: The due_date of this TodoCreate [Optional].

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | HTTPValidationError | Todo]
    """

    kwargs = _get_kwargs(
        body=body,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient | Client,
    body: TodoCreate | Unset = UNSET,
) -> Error | HTTPValidationError | Todo | None:
    """TODO作成

     新しいTODOを作成する

    Args:
        body (TodoCreate | Unset): NOTE: This class is auto generated by OpenAPI Generator
            (https://openapi-generator.tech).

            Do not edit the class manually.

            TodoCreate - a model defined in OpenAPI

                project_id: The project_id of this TodoCreate [Optional].
                worker_id: The worker_id of this TodoCreate.
                agent_id: The agent_id of this TodoCreate [Optional].
                title: The title of this TodoCreate.
                description: The description of this TodoCreate [Optional].
                status: The status of this TodoCreate [Optional].
                priority: The priority of this TodoCreate [Optional].
                due_date: The due_date of this TodoCreate [Optional].

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | HTTPValidationError | Todo
    """

    return (
        await asyncio_detailed(
            client=client,
            body=body,
        )
    ).parsed
