from http import HTTPStatus
from typing import Any

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.current_project_response import CurrentProjectResponse
from ...models.current_project_set import CurrentProjectSet
from ...models.error import Error
from ...models.http_validation_error import HTTPValidationError
from ...types import UNSET, Response, Unset


def _get_kwargs(
    *,
    body: CurrentProjectSet | Unset = UNSET,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}

    _kwargs: dict[str, Any] = {
        "method": "put",
        "url": "/current-project",
    }

    if not isinstance(body, Unset):
        _kwargs["json"] = body.to_dict()

    headers["Content-Type"] = "application/json"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> CurrentProjectResponse | Error | HTTPValidationError | None:
    if response.status_code == 200:
        response_200 = CurrentProjectResponse.from_dict(response.json())

        return response_200

    if response.status_code == 404:
        response_404 = Error.from_dict(response.json())

        return response_404

    if response.status_code == 422:
        response_422 = HTTPValidationError.from_dict(response.json())

        return response_422

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[CurrentProjectResponse | Error | HTTPValidationError]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient | Client,
    body: CurrentProjectSet | Unset = UNSET,
) -> Response[CurrentProjectResponse | Error | HTTPValidationError]:
    """現在のプロジェクト設定

     現在のプロジェクトを設定する。新規作成されるTODOはこのプロジェクトに紐付けられます。

    Args:
        body (CurrentProjectSet | Unset): NOTE: This class is auto generated by OpenAPI Generator
            (https://openapi-generator.tech).

            Do not edit the class manually.

            CurrentProjectSet - a model defined in OpenAPI

                project_id: The project_id of this CurrentProjectSet [Optional].

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[CurrentProjectResponse | Error | HTTPValidationError]
    """

    kwargs = _get_kwargs(
        body=body,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient | Client,
    body: CurrentProjectSet | Unset = UNSET,
) -> CurrentProjectResponse | Error | HTTPValidationError | None:
    """現在のプロジェクト設定

     現在のプロジェクトを設定する。新規作成されるTODOはこのプロジェクトに紐付けられます。

    Args:
        body (CurrentProjectSet | Unset): NOTE: This class is auto generated by OpenAPI Generator
            (https://openapi-generator.tech).

            Do not edit the class manually.

            CurrentProjectSet - a model defined in OpenAPI

                project_id: The project_id of this CurrentProjectSet [Optional].

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        CurrentProjectResponse | Error | HTTPValidationError
    """

    return sync_detailed(
        client=client,
        body=body,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient | Client,
    body: CurrentProjectSet | Unset = UNSET,
) -> Response[CurrentProjectResponse | Error | HTTPValidationError]:
    """現在のプロジェクト設定

     現在のプロジェクトを設定する。新規作成されるTODOはこのプロジェクトに紐付けられます。

    Args:
        body (CurrentProjectSet | Unset): NOTE: This class is auto generated by OpenAPI Generator
            (https://openapi-generator.tech).

            Do not edit the class manually.

            CurrentProjectSet - a model defined in OpenAPI

                project_id: The project_id of this CurrentProjectSet [Optional].

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[CurrentProjectResponse | Error | HTTPValidationError]
    """

    kwargs = _get_kwargs(
        body=body,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient | Client,
    body: CurrentProjectSet | Unset = UNSET,
) -> CurrentProjectResponse | Error | HTTPValidationError | None:
    """現在のプロジェクト設定

     現在のプロジェクトを設定する。新規作成されるTODOはこのプロジェクトに紐付けられます。

    Args:
        body (CurrentProjectSet | Unset): NOTE: This class is auto generated by OpenAPI Generator
            (https://openapi-generator.tech).

            Do not edit the class manually.

            CurrentProjectSet - a model defined in OpenAPI

                project_id: The project_id of this CurrentProjectSet [Optional].

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        CurrentProjectResponse | Error | HTTPValidationError
    """

    return (
        await asyncio_detailed(
            client=client,
            body=body,
        )
    ).parsed
