from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, BinaryIO, TextIO, TYPE_CHECKING, Generator

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

from ..types import UNSET, Unset
from dateutil.parser import isoparse
from typing import cast
import datetime






T = TypeVar("T", bound="TodoSubtask")



@_attrs_define
class TodoSubtask:
    """ NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    TodoSubtask - a model defined in OpenAPI

        id: The id of this TodoSubtask.
        uuid: The uuid of this TodoSubtask [Optional].
        todo_id: The todo_id of this TodoSubtask.
        title: The title of this TodoSubtask.
        description: The description of this TodoSubtask [Optional].
        status: The status of this TodoSubtask.
        sort_order: The sort_order of this TodoSubtask.
        completed_at: The completed_at of this TodoSubtask [Optional].
        created_at: The created_at of this TodoSubtask.
        updated_at: The updated_at of this TodoSubtask.

        Attributes:
            id (int):
            todo_id (int):
            title (str):
            status (str):
            sort_order (int):
            created_at (datetime.datetime):
            updated_at (datetime.datetime):
            uuid (None | str | Unset):
            description (None | str | Unset):
            completed_at (datetime.datetime | None | Unset):
     """

    id: int
    todo_id: int
    title: str
    status: str
    sort_order: int
    created_at: datetime.datetime
    updated_at: datetime.datetime
    uuid: None | str | Unset = UNSET
    description: None | str | Unset = UNSET
    completed_at: datetime.datetime | None | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)





    def to_dict(self) -> dict[str, Any]:
        id = self.id

        todo_id = self.todo_id

        title = self.title

        status = self.status

        sort_order = self.sort_order

        created_at = self.created_at.isoformat()

        updated_at = self.updated_at.isoformat()

        uuid: None | str | Unset
        if isinstance(self.uuid, Unset):
            uuid = UNSET
        else:
            uuid = self.uuid

        description: None | str | Unset
        if isinstance(self.description, Unset):
            description = UNSET
        else:
            description = self.description

        completed_at: None | str | Unset
        if isinstance(self.completed_at, Unset):
            completed_at = UNSET
        elif isinstance(self.completed_at, datetime.datetime):
            completed_at = self.completed_at.isoformat()
        else:
            completed_at = self.completed_at


        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({
            "id": id,
            "todo_id": todo_id,
            "title": title,
            "status": status,
            "sort_order": sort_order,
            "created_at": created_at,
            "updated_at": updated_at,
        })
        if uuid is not UNSET:
            field_dict["uuid"] = uuid
        if description is not UNSET:
            field_dict["description"] = description
        if completed_at is not UNSET:
            field_dict["completed_at"] = completed_at

        return field_dict



    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        id = d.pop("id")

        todo_id = d.pop("todo_id")

        title = d.pop("title")

        status = d.pop("status")

        sort_order = d.pop("sort_order")

        created_at = isoparse(d.pop("created_at"))




        updated_at = isoparse(d.pop("updated_at"))




        def _parse_uuid(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        uuid = _parse_uuid(d.pop("uuid", UNSET))


        def _parse_description(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        description = _parse_description(d.pop("description", UNSET))


        def _parse_completed_at(data: object) -> datetime.datetime | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                completed_at_type_0 = isoparse(data)



                return completed_at_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.datetime | None | Unset, data)

        completed_at = _parse_completed_at(d.pop("completed_at", UNSET))


        todo_subtask = cls(
            id=id,
            todo_id=todo_id,
            title=title,
            status=status,
            sort_order=sort_order,
            created_at=created_at,
            updated_at=updated_at,
            uuid=uuid,
            description=description,
            completed_at=completed_at,
        )


        todo_subtask.additional_properties = d
        return todo_subtask

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
